"""初始迁移——创建所有核心表（项目、用户、Agent配置、日志、告警、评测等）"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bcae9e0f36a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('api_key', sa.String(length=64), nullable=False),
    sa.Column('base_url', sa.String(length=256), nullable=False),
    sa.Column('api_key_upstream', sa.String(length=256), nullable=False),
    sa.Column('agent_model', sa.String(length=100), nullable=True),
    sa.Column('agent_api_key', sa.String(length=256), nullable=True),
    sa.Column('agent_base_url', sa.String(length=512), nullable=True),
    sa.Column('detection_config', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_projects_api_key'), 'projects', ['api_key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('agent_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('tools', sa.JSON(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('max_iterations', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_configs_project_id'), 'agent_configs', ['project_id'], unique=False)
    op.create_table('agent_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('trace_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('node_name', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_logs_created_at'), 'agent_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_logs_level'), 'agent_logs', ['level'], unique=False)
    op.create_index(op.f('ix_agent_logs_project_id'), 'agent_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_agent_logs_trace_id'), 'agent_logs', ['trace_id'], unique=False)
    op.create_table('agent_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=20), nullable=False),
    sa.Column('time_start', sa.DateTime(), nullable=False),
    sa.Column('time_end', sa.DateTime(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=False),
    sa.Column('findings', sa.Text(), nullable=False),
    sa.Column('suggestions', sa.Text(), nullable=False),
    sa.Column('estimated_savings_monthly', sa.Float(), nullable=True),
    sa.Column('agent_input_tokens', sa.Integer(), nullable=False),
    sa.Column('agent_output_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_reports_project_id'), 'agent_reports', ['project_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('trace_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_project_id'), 'alerts', ['project_id'], unique=False)
    op.create_table('api_calls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('endpoint', sa.String(length=50), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_creation_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('prompt_preview', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_calls_project_id'), 'api_calls', ['project_id'], unique=False)
    op.create_index(op.f('ix_api_calls_request_hash'), 'api_calls', ['request_hash'], unique=False)
    op.create_index(op.f('ix_api_calls_timestamp'), 'api_calls', ['timestamp'], unique=False)
    op.create_index('ix_project_timestamp', 'api_calls', ['project_id', 'timestamp'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('tool_args', sa.JSON(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requester', sa.String(length=100), nullable=True),
    sa.Column('reviewer', sa.String(length=100), nullable=True),
    sa.Column('reviewer_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_created_at'), 'approval_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_approval_requests_project_id'), 'approval_requests', ['project_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_trace_id'), 'approval_requests', ['trace_id'], unique=False)
    op.create_table('bait_credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('key_type', sa.String(length=30), nullable=False),
    sa.Column('key_value', sa.String(length=256), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bait_credentials_project_id'), 'bait_credentials', ['project_id'], unique=False)
    op.create_table('detection_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('endpoint', sa.String(length=50), nullable=True),
    sa.Column('request_hash', sa.String(length=64), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_alerts_detected_at'), 'detection_alerts', ['detected_at'], unique=False)
    op.create_index(op.f('ix_detection_alerts_project_id'), 'detection_alerts', ['project_id'], unique=False)
    op.create_index('ix_detection_project_time', 'detection_alerts', ['project_id', 'detected_at'], unique=False)
    op.create_index('ix_detection_type', 'detection_alerts', ['project_id', 'alert_type'], unique=False)
    op.create_table('eval_sets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scoring_method', sa.String(length=20), nullable=False),
    sa.Column('pass_threshold', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_sets_project_id'), 'eval_sets', ['project_id'], unique=False)
    op.create_table('project_budgets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('max_tokens_per_day', sa.Integer(), nullable=False),
    sa.Column('max_cost_per_month', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('max_tokens_per_run', sa.Integer(), nullable=False),
    sa.Column('max_concurrent_runs', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_budgets_project_id'), 'project_budgets', ['project_id'], unique=True)
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trace_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input', sa.JSON(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=14, scale=8), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['agent_configs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_project_id'), 'agent_runs', ['project_id'], unique=False)
    op.create_index('ix_agent_runs_project_started', 'agent_runs', ['project_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_agent_runs_started_at'), 'agent_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_index(op.f('ix_agent_runs_trace_id'), 'agent_runs', ['trace_id'], unique=True)
    op.create_table('eval_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('eval_set_id', sa.Integer(), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('expected_output', sa.Text(), nullable=True),
    sa.Column('expected_tools', sa.JSON(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['eval_set_id'], ['eval_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_cases_eval_set_id'), 'eval_cases', ['eval_set_id'], unique=False)
    op.create_table('eval_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('eval_set_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('tools', sa.JSON(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_cases', sa.Integer(), nullable=False),
    sa.Column('passed_cases', sa.Integer(), nullable=False),
    sa.Column('average_score', sa.Float(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('baseline_run_id', sa.Integer(), nullable=True),
    sa.Column('regression_detected', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['baseline_run_id'], ['eval_runs.id'], ),
    sa.ForeignKeyConstraint(['eval_set_id'], ['eval_sets.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_runs_eval_set_id'), 'eval_runs', ['eval_set_id'], unique=False)
    op.create_index(op.f('ix_eval_runs_project_id'), 'eval_runs', ['project_id'], unique=False)
    op.create_table('agent_node_traces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trace_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('node_name', sa.String(length=100), nullable=False),
    sa.Column('node_type', sa.String(length=50), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('input', sa.JSON(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('llm_thought', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('token_usage', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trace_id'], ['agent_runs.trace_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_node_traces_trace_id'), 'agent_node_traces', ['trace_id'], unique=False)
    op.create_index('ix_node_traces_trace_seq', 'agent_node_traces', ['trace_id', 'sequence'], unique=False)
    op.create_table('eval_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('eval_run_id', sa.Integer(), nullable=False),
    sa.Column('eval_case_id', sa.Integer(), nullable=False),
    sa.Column('actual_output', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['eval_case_id'], ['eval_cases.id'], ),
    sa.ForeignKeyConstraint(['eval_run_id'], ['eval_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_scores_eval_run_id'), 'eval_scores', ['eval_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eval_scores_eval_run_id'), table_name='eval_scores')
    op.drop_table('eval_scores')
    op.drop_index('ix_node_traces_trace_seq', table_name='agent_node_traces')
    op.drop_index(op.f('ix_agent_node_traces_trace_id'), table_name='agent_node_traces')
    op.drop_table('agent_node_traces')
    op.drop_index(op.f('ix_eval_runs_project_id'), table_name='eval_runs')
    op.drop_index(op.f('ix_eval_runs_eval_set_id'), table_name='eval_runs')
    op.drop_table('eval_runs')
    op.drop_index(op.f('ix_eval_cases_eval_set_id'), table_name='eval_cases')
    op.drop_table('eval_cases')
    op.drop_index(op.f('ix_agent_runs_trace_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_started_at'), table_name='agent_runs')
    op.drop_index('ix_agent_runs_project_started', table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_project_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_project_budgets_project_id'), table_name='project_budgets')
    op.drop_table('project_budgets')
    op.drop_index(op.f('ix_eval_sets_project_id'), table_name='eval_sets')
    op.drop_table('eval_sets')
    op.drop_index('ix_detection_type', table_name='detection_alerts')
    op.drop_index('ix_detection_project_time', table_name='detection_alerts')
    op.drop_index(op.f('ix_detection_alerts_project_id'), table_name='detection_alerts')
    op.drop_index(op.f('ix_detection_alerts_detected_at'), table_name='detection_alerts')
    op.drop_table('detection_alerts')
    op.drop_index(op.f('ix_bait_credentials_project_id'), table_name='bait_credentials')
    op.drop_table('bait_credentials')
    op.drop_index(op.f('ix_approval_requests_trace_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_project_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_created_at'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index('ix_project_timestamp', table_name='api_calls')
    op.drop_index(op.f('ix_api_calls_timestamp'), table_name='api_calls')
    op.drop_index(op.f('ix_api_calls_request_hash'), table_name='api_calls')
    op.drop_index(op.f('ix_api_calls_project_id'), table_name='api_calls')
    op.drop_table('api_calls')
    op.drop_index(op.f('ix_alerts_project_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_agent_reports_project_id'), table_name='agent_reports')
    op.drop_table('agent_reports')
    op.drop_index(op.f('ix_agent_logs_trace_id'), table_name='agent_logs')
    op.drop_index(op.f('ix_agent_logs_project_id'), table_name='agent_logs')
    op.drop_index(op.f('ix_agent_logs_level'), table_name='agent_logs')
    op.drop_index(op.f('ix_agent_logs_created_at'), table_name='agent_logs')
    op.drop_table('agent_logs')
    op.drop_index(op.f('ix_agent_configs_project_id'), table_name='agent_configs')
    op.drop_table('agent_configs')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_api_key'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
